### PR TITLE
Update mysql prefix on install

### PR DESCRIPTION
**Pull request by ryanmjt**
See #10.

This is untested (authored on GitHub web editor), but should work or at least be a good starting point.

### CODE REVIEW

**Comment by tanner0101** [comment]
The file should be changed [here](https://github.com/vapor/cmysql/blob/master/macos.pc) instead of doing a find and replace with homebrew. 

Requesting @vzsg since this was changed recently. I think it should all just work w/o the change proposed in this PR.

**Comment by ryanmjt** [comment]
It doesn't really make sense to change it there though, this is a homebrew specific thing, and every user's homebrew location could be different, so it has to be handled on install I believe.

**Comment by tanner0101** [comment]
Aha, I see now. It's dynamic. 

> This should be replaced when installed from this tap so that it uses whatever the homebrew prefix path is

Can you elaborate on why this is necessary / better?

**Comment by ryanmjt** [comment]
I'm not sure you understand the problem this patch is solving. Where would you propose this change be? Homebrew allows you to install to any arbitrary prefix, and only homebrew's `Formula[xyz].opt_prefix` (on the user's machine, at runtime) knows what that prefix is.

**Comment by ryanmjt** [comment]
To elaborate, this was an issue we (me, @vzsg, and matz) discussed on Slack and right now my workaround is to manually modify that file. My homebrew installation is not in `/usr/local`, and so even installing your `cmysql` does not fix build errors, since it you have it hardcoded to look for mysql in the wrong location.

**Comment by tanner0101** [comment]
> My homebrew installation is not in /usr/local

That's the part I was missing. (that custom homebrew installation paths are not supported). 

> To elaborate, this was an issue we (me, @vzsg, and @matz) discussed on Slack

Info from that convo should be added to #10 if possible

**Comment by vzsg** [comment]
@ryanmjt is right, this whole issue is on a different level.

I don't know how to test formulas though, so I can't vouch for the change by itself. But if other formulas use this expression, then it should be fine by me.

**Comment by 0xTim** [comment]
Closing due to inactivity

**Pull request closed without merging**
